[tool.poetry]
name = "mango"
version = "0.1.0"
description = ""
authors = ["Артур Лагунов <a.lagunov@ktsstudio.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
