"""read_status

Revision ID: d7192bb5b567
Revises: 5dcce4ef7e4f
Create Date: 2025-03-28 06:44:50.514645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7192bb5b567'
down_revision = '5dcce4ef7e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    # ### end Alembic commands ###
